#!/usr/bin/env bash
#
# Custom Git workflow for completing work on a branch.
#
# 
#

set -e

if [[ $1 ]]; then
	BRANCH=$1
else
	# Defaults to current branch
	BRANCH=`git rev-parse --abbrev-ref HEAD`
fi

if [[ $BRANCH ]]; then
	set -x
	git pull origin $BRANCH
	git submodule update --remote --recursive
	set +x
else
	echo ""
	echo "ERROR"
	echo ""
	exit
fi
